import type { Team } from "./types";

// name, nickname, abbr, conference, primary, secondary, siteName, state, pull
const raw: [string, string, string, string, string, string, string, string, number][] = [
  ["Alabama", "Crimson Tide", "ALA", "SEC", "#9E1B32", "#FFFFFF", "TideIllustrated", "AL", 0.95],
  ["Georgia", "Bulldogs", "UGA", "SEC", "#BA0C2F", "#000000", "UGASports", "GA", 1.0],
  ["Ohio State", "Buckeyes", "OSU", "Big Ten", "#BB0000", "#666666", "DotTheEyes", "OH", 0.98],
  ["Texas", "Longhorns", "TEX", "SEC", "#BF5700", "#FFFFFF", "OrangeBloods", "TX", 0.97],
  ["LSU", "Tigers", "LSU", "SEC", "#461D7C", "#FDD023", "TigerDetails", "LA", 0.93],
  ["Oregon", "Ducks", "ORE", "Big Ten", "#154733", "#FEE123", "DuckTerritory", "OR", 0.92],
  ["Michigan", "Wolverines", "MICH", "Big Ten", "#00274C", "#FFCB05", "TheWolverine", "MI", 0.9],
  ["Texas A&M", "Aggies", "TAMU", "SEC", "#500000", "#FFFFFF", "AggieYell", "TX", 0.9],
  ["Notre Dame", "Fighting Irish", "ND", "Independent", "#0C2340", "#C99700", "BlueAndGold", "IN", 0.88],
  ["Penn State", "Nittany Lions", "PSU", "Big Ten", "#041E42", "#FFFFFF", "BlueWhiteIllustrated", "PA", 0.86],
  ["Tennessee", "Volunteers", "TENN", "SEC", "#FF8200", "#FFFFFF", "VolQuest", "TN", 0.87],
  ["Auburn", "Tigers", "AUB", "SEC", "#0C2340", "#E87722", "AuburnSports", "AL", 0.85],
  ["Florida", "Gators", "FLA", "SEC", "#0021A5", "#FA4616", "1standTenFlorida", "FL", 0.86],
  ["Miami", "Hurricanes", "MIA", "ACC", "#F47321", "#005030", "CaneSport", "FL", 0.87],
  ["Florida State", "Seminoles", "FSU", "ACC", "#782F40", "#CEB888", "Warchant", "FL", 0.84],
  ["Clemson", "Tigers", "CLEM", "ACC", "#F56600", "#522D80", "TigerIllustrated", "SC", 0.84],
  ["USC", "Trojans", "USC", "Big Ten", "#990000", "#FFC72C", "TrojanSports", "CA", 0.89],
  ["Oklahoma", "Sooners", "OU", "SEC", "#841617", "#FDF9D8", "SoonerScoop", "OK", 0.85],
  ["Ole Miss", "Rebels", "MISS", "SEC", "#CE1126", "#14213D", "RebelGrove", "MS", 0.8],
  ["South Carolina", "Gamecocks", "SC", "SEC", "#73000A", "#000000", "GamecockCentral", "SC", 0.8],
  ["Missouri", "Tigers", "MIZ", "SEC", "#F1B82D", "#000000", "PowerMizzou", "MO", 0.74],
  ["Kentucky", "Wildcats", "UK", "SEC", "#0033A0", "#FFFFFF", "CatsIllustrated", "KY", 0.7],
  ["Arkansas", "Razorbacks", "ARK", "SEC", "#9D2235", "#FFFFFF", "HawgBeat", "AR", 0.72],
  ["Mississippi State", "Bulldogs", "MSST", "SEC", "#660000", "#FFFFFF", "GenesPage", "MS", 0.66],
  ["Vanderbilt", "Commodores", "VAN", "SEC", "#866D4B", "#000000", "VandySports", "TN", 0.55],
  ["Nebraska", "Cornhuskers", "NEB", "Big Ten", "#E41C38", "#FFFFFF", "HuskerOnline", "NE", 0.76],
  ["Wisconsin", "Badgers", "WIS", "Big Ten", "#C5050C", "#FFFFFF", "BadgerBlitz", "WI", 0.7],
  ["Iowa", "Hawkeyes", "IOWA", "Big Ten", "#FFCD00", "#000000", "HawkeyeReport", "IA", 0.66],
  ["Michigan State", "Spartans", "MSU", "Big Ten", "#18453B", "#FFFFFF", "SpartanMag", "MI", 0.7],
  ["Washington", "Huskies", "WASH", "Big Ten", "#4B2E83", "#B7A57A", "DawgmanReport", "WA", 0.78],
  ["UCLA", "Bruins", "UCLA", "Big Ten", "#2D68C4", "#F2A900", "BruinBlitz", "CA", 0.74],
  ["Illinois", "Fighting Illini", "ILL", "Big Ten", "#13294B", "#E84A27", "OrangeAndBlueNews", "IL", 0.62],
  ["Indiana", "Hoosiers", "IND", "Big Ten", "#990000", "#EEEDEB", "TheHoosier", "IN", 0.64],
  ["Minnesota", "Golden Gophers", "MINN", "Big Ten", "#7A0019", "#FFCC33", "GopherIllustrated", "MN", 0.6],
  ["Rutgers", "Scarlet Knights", "RUTG", "Big Ten", "#CC0033", "#FFFFFF", "TheKnightReport", "NJ", 0.6],
  ["Maryland", "Terrapins", "MD", "Big Ten", "#E03A3E", "#FFD520", "TerrapinSportsReport", "MD", 0.62],
  ["Northwestern", "Wildcats", "NW", "Big Ten", "#4E2A84", "#FFFFFF", "WildcatReport", "IL", 0.5],
  ["Purdue", "Boilermakers", "PUR", "Big Ten", "#CEB888", "#000000", "GoldandBlack", "IN", 0.56],
  ["North Carolina", "Tar Heels", "UNC", "ACC", "#7BAFD4", "#FFFFFF", "TarHeelIllustrated", "NC", 0.78],
  ["NC State", "Wolfpack", "NCST", "ACC", "#CC0000", "#FFFFFF", "ThePackPride", "NC", 0.66],
  ["Louisville", "Cardinals", "LOU", "ACC", "#AD0000", "#000000", "CardinalSports", "KY", 0.68],
  ["Virginia Tech", "Hokies", "VT", "ACC", "#630031", "#CF4420", "TechSideline", "VA", 0.62],
  ["Pitt", "Panthers", "PITT", "ACC", "#003594", "#FFB81C", "PantherLair", "PA", 0.6],
  ["Duke", "Blue Devils", "DUKE", "ACC", "#003087", "#FFFFFF", "DevilsIllustrated", "NC", 0.6],
  ["SMU", "Mustangs", "SMU", "ACC", "#0033A0", "#C8102E", "PonyStampede", "TX", 0.64],
  ["Colorado", "Buffaloes", "COLO", "Big 12", "#CFB87C", "#000000", "CUSportsReport", "CO", 0.72],
  ["Utah", "Utes", "UTAH", "Big 12", "#CC0000", "#FFFFFF", "UteNation", "UT", 0.64],
  ["Arizona State", "Sun Devils", "ASU", "Big 12", "#8C1D40", "#FFC627", "DevilsDigest", "AZ", 0.66],
  ["Kansas State", "Wildcats", "KSU", "Big 12", "#512888", "#FFFFFF", "EMAWOnline", "KS", 0.6],
  ["TCU", "Horned Frogs", "TCU", "Big 12", "#4D1979", "#A3A9AC", "PurpleMenace", "TX", 0.66],
  ["Baylor", "Bears", "BAY", "Big 12", "#154734", "#FFB81C", "SicEmSports", "TX", 0.62],
  ["Texas Tech", "Red Raiders", "TTU", "Big 12", "#CC0000", "#000000", "RedRaiderSports", "TX", 0.68],
  ["Oklahoma State", "Cowboys", "OKST", "Big 12", "#FF7300", "#000000", "PokesReport", "OK", 0.6],
  ["Kansas", "Jayhawks", "KU", "Big 12", "#0051BA", "#E8000D", "JayhawkSlant", "KS", 0.6],
  ["BYU", "Cougars", "BYU", "Big 12", "#002E5D", "#FFFFFF", "CougarNation", "UT", 0.6],
  ["Boise State", "Broncos", "BSU", "Mountain West", "#0033A0", "#D64309", "BroncoBlitz", "ID", 0.5],
];

export const TEAMS: Team[] = raw.map(([name, nickname, abbr, conference, primary, secondary, siteName, state, pull]) => ({
  slug: name.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-"),
  name,
  nickname,
  abbr,
  conference,
  primary,
  secondary,
  siteName,
  state,
  pull,
}));

export const TEAM_BY_SLUG: Record<string, Team> = Object.fromEntries(TEAMS.map((t) => [t.slug, t]));

export function getTeam(slug: string): Team | undefined {
  return TEAM_BY_SLUG[slug];
}
